# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistantUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_assistantUi(object):
    def setupUi(self, assistantUi):
        assistantUi.setObjectName("assistantUi")
        assistantUi.resize(1265, 945)
        self.centralwidget = QtWidgets.QWidget(assistantUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, -5, 1261, 931))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assistant_img/212508.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 530, 421, 261))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assistant_img/3Hb_eh.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 471, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assistant_img/SpanishFirstAmmonite-size_restricted.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1000, 70, 231, 71))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:30px;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(770, 70, 231, 71))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:30px;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 220, 291, 231))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("assistant_img/hud_2.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(830, 240, 151, 151))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assistant_img/c572a4f5-9930-44d3-9818-1d28ab0232b7.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1070, 530, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:transparent;\n"
"background-color: qlineargradient(spread:pad, x1:0.08, y1:0.0738636, x2:1, y2:1, stop:0.432836 rgba(0, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:none;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 620, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"background-color: qlineargradient(spread:pad, x1:0.08, y1:0.0738636, x2:1, y2:1, stop:0.18408 rgba(255, 255, 255, 255), stop:1 rgba(170, 0, 0, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        assistantUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(assistantUi)
        self.statusbar.setObjectName("statusbar")
        assistantUi.setStatusBar(self.statusbar)

        self.retranslateUi(assistantUi)
        QtCore.QMetaObject.connectSlotsByName(assistantUi)

    def retranslateUi(self, assistantUi):
        _translate = QtCore.QCoreApplication.translate
        assistantUi.setWindowTitle(_translate("assistantUi", "MainWindow"))
        self.pushButton.setText(_translate("assistantUi", "START"))
        self.pushButton_2.setText(_translate("assistantUi", "EXIT"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assistantUi = QtWidgets.QMainWindow()
    ui = Ui_assistantUi()
    ui.setupUi(assistantUi)
    assistantUi.show()
    sys.exit(app.exec_())
